# Support XMRT - Financial Privacy & Liberty
github: DevGruGold
bitcoin: "bc1qxmrt..."  # Add your BTC address
ethereum: "0xXMRT..."   # Add your ETH address
custom: ["https://xmrt.io/donate", "https://xmrt.io/support-privacy"]
